# Generated by Django 4.0.3 on 2022-03-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='videos/')),
            ],
        ),
    ]
